"""Update field is_archived on is_active in table accounts

Revision ID: 3bc66424b8bd
Revises: 3e69a27874db
Create Date: 2026-04-07 22:29:35.415178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc66424b8bd'
down_revision: Union[str, Sequence[str], None] = '3e69a27874db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('accounts', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'is_active')
    # ### end Alembic commands ###
