"""Add field is_active in table Transaction

Revision ID: 3e69a27874db
Revises: d8847d1c1ae1
Create Date: 2026-04-07 16:23:26.730993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e69a27874db'
down_revision: Union[str, Sequence[str], None] = 'd8847d1c1ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_active')
    # ### end Alembic commands ###
