"""Add user model

Revision ID: 45ae1c94efd9
Revises: 58d437756ffe
Create Date: 2026-03-25 08:49:41.382580

"""
from typing import Sequence, Union

from backend.alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45ae1c94efd9'
down_revision: Union[str, Sequence[str], None] = '58d437756ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM accounts") 
    op.execute("DELETE FROM categories") 
    op.execute("DELETE FROM transactions") 
    op.execute("DELETE FROM users") 
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('transactions', 'updated_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
