"""create users table

Revision ID: 58d437756ffe
Revises: 18348f5d5be1
Create Date: 2026-03-23 22:37:29.138702

"""
from typing import Sequence, Union

from backend.alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d437756ffe'
down_revision: Union[str, Sequence[str], None] = '18348f5d5be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
