"""Update accounts difault is_active true

Revision ID: 96155b255dd3
Revises: aa5218557122
Create Date: 2026-04-10 14:13:38.187586

"""
from typing import Sequence, Union

from backend.alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96155b255dd3'
down_revision: Union[str, Sequence[str], None] = 'aa5218557122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
