"""Update category

Revision ID: aa5218557122
Revises: 3bc66424b8bd
Create Date: 2026-04-09 17:17:39.902554

"""
from typing import Sequence, Union

from backend.alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5218557122'
down_revision: Union[str, Sequence[str], None] = '3bc66424b8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
