"""add field role in table user

Revision ID: d2ba6a0bb710
Revises: a5fcc0196b63
Create Date: 2026-03-30 12:42:59.953579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ba6a0bb710'
down_revision: Union[str, Sequence[str], None] = 'a5fcc0196b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM accounts") 
    op.execute("DELETE FROM categories") 
    op.execute("DELETE FROM transactions") 
    op.execute("DELETE FROM users") 
    op.add_column('transactions', sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('transactions', 'ammount')
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('transactions', sa.Column('ammount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'amount')
    # ### end Alembic commands ###
