"""Update field date as transactions_date

Revision ID: d8847d1c1ae1
Revises: d2ba6a0bb710
Create Date: 2026-04-07 16:03:38.276315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8847d1c1ae1'
down_revision: Union[str, Sequence[str], None] = 'd2ba6a0bb710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.DATE(), nullable=False))
    op.drop_column('transactions', 'date')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.add_column('transactions', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
