"""Create table name Transfer

Revision ID: df7a02c04fb1
Revises: 5a1334f2c7c3
Create Date: 2026-08-24 13:19:49.284380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df7a02c04fb1'
down_revision: Union[str, Sequence[str], None] = '5a1334f2c7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('transfer_date', sa.DATE(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix__transfer_date', 'transfers', ['transfer_date'], unique=False)
    op.create_index('ix_transfer_from_account_id', 'transfers', ['from_account_id'], unique=False)
    op.create_index('ix_transfer_to_account_id', 'transfers', ['to_account_id'], unique=False)
    op.create_index('ix_transfer_user_id', 'transfers', ['user_id'], unique=False)
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_index('ix_transfer_user_id', table_name='transfers')
    op.drop_index('ix_transfer_to_account_id', table_name='transfers')
    op.drop_index('ix_transfer_from_account_id', table_name='transfers')
    op.drop_index('ix__transfer_date', table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
